#ifndef GUARD_BATTERYLESS_H
#define GUARD_BATTERYLESS_H

#define BATTERYLESS

#define BATTERYLESS_NOP asm("mov r8, r8")
#define BATTERYLESS_NOP_2 BATTERYLESS_NOP; BATTERYLESS_NOP
#define BATTERYLESS_NOP_3 BATTERYLESS_NOP_2; BATTERYLESS_NOP
#define BATTERYLESS_NOP_4 BATTERYLESS_NOP_3; BATTERYLESS_NOP
#define BATTERYLESS_NOP_5 BATTERYLESS_NOP_4; BATTERYLESS_NOP
#define BATTERYLESS_NOP_6 BATTERYLESS_NOP_5; BATTERYLESS_NOP
#define BATTERYLESS_NOP_7 BATTERYLESS_NOP_6; BATTERYLESS_NOP
#define BATTERYLESS_NOP_8 BATTERYLESS_NOP_7; BATTERYLESS_NOP
#define BATTERYLESS_NOP_9 BATTERYLESS_NOP_8; BATTERYLESS_NOP

#endif // GUARD_BATTERYLESS_H